[package]
name = "bszet-image"
version = "0.0.0-git"
edition = "2021"

[dependencies]
fantoccini = { version = "0.20.0-rc.7", default-features = false }
hyper = { version = "0.14", features = ["client"], default-features = false }
anyhow = "1.0"

[dev-dependencies]
tokio = { version = "1.35", default-features = false, features = ["macros", "test-util"] }
